### ISSUE TITLE
quicksurvey dependency on pyephem

### ISSUE THREAD

**Issue by forero** [desihub/quicksurvey_example#2]
Quicksurvey has a dependency on pyephem, what are the instructions to use that module on NERSC?

**Comment by sbailey** [comment]
pyephem is included with the base set of external dependencies installed with desi-conda at NERSC.
If you want just those external python dependencies but not any of the `desi*` packages because you are using your own development copies:
```bash
module use /global/common/edison/contrib/desi/modulefiles/
module load desi-conda
```

If you want to load that plus a full set of desi modules:
```bash
module use /global/common/edison/contrib/desi/modulefiles/
module load desimodules
```
Note: `source /project/projectdirs/desi/software/desi_environment.sh` is equivalent to that, with the additional benefit of taking care of the difference between edison, cori, and data transfer nodes, though currently we only have the full stack installed on edison.

If you want to replace a desi package with your own development copy, e.g. desisim in your $SCRATCH directory:
```
#- Load a full set of desi packages and external dependencies
module use /global/common/edison/contrib/desi/modulefiles/
module load desimodules

#- Unload and replace specific ones with your development copy
module unload desisim
export PYTHONPATH=$SCRATCH/desisim/py:$PYTHONPATH
export PATH=$SCRATCH/desisim/bin:$PYTHONPATH
```
Also see https://desi.lbl.gov/trac/wiki/Pipeline/GettingStarted/NERSC

**Comment by forero** [comment]
Good. I had `module load desi-conda/3.5-20160829`, which is clearly and old version that didn't include pyephem.
