### ISSUE TITLE
incomplete quicksurvey instruction?

### ISSUE THREAD

**Issue by forero** [desihub/quicksurvey_example#3]
This instruction
```bash
time quicksurvey --output_dir output/  \
  --targets_dir input/  \
  --fiberassign_exec `which fiberassign` \
  --template_fiberassign input/template_fiberassign.txt \
  --obsconditions surveysim/obslist_all.fits \
  --fiberassign_dates input/fiberassign_dates.txt
```

fails with
`NameError: n_epochs was not setNameError: n_epochs was not set`

are there other options to add or is it a bug in quicksurvey?

**Comment by forero** [comment]
are there other options to add or is it a bug in `quicksurvey`?

**Comment by sbailey** [comment]
Which git hash / branch are you using for desisim?  I just re-confirmed that the instructions work for `/global/common/edison/contrib/desi/code/desisim/0.17.0/bin/quicksurvey` as installed at NERSC.  Are you possibly using a development copy that you need to git pull from master?  This issue was broken after PR #190 was merged on Nov 30, but was fixed with one of the commits on Dec 1.

**Comment by forero** [comment]
Found the problem. I made a mistake copy-pasting the command, I missed the last line `--fiberassign_dates`. Everything works fine.
